import json
import os
from pathlib import Path

from config import SOURCE_JSON, PROMPTS_DIR, WEEK_START, WEEK_END


def load_source():
    with open(SOURCE_JSON, "r", encoding="utf-8") as file:
        return json.load(file)


def build_extraction_input(source):
    # Preserve the source sections as evidence. We do not ask the model to
    # infer from a summary generated by another model.
    parts = [
        "DATASET WEEK: {} to {}".format(WEEK_START, WEEK_END),
        "EXECUTIVE: Arjun Malhotra",
        ""
    ]

    for section_name, section_text in source["sections"].items():
        if section_name == "prototype_note":
            continue
        parts.append("=== {} ===".format(section_name.upper()))
        parts.append(section_text)
        parts.append("")

    return "\n".join(parts)


def load_prompt():
    prompt_path = PROMPTS_DIR / "extraction_prompt.txt"
    return prompt_path.read_text(encoding="utf-8")


def extract_with_openai(model=None):
    """
    LLM-backed Phase C extraction.

    Requires:
        OPENAI_API_KEY environment variable

    Optional:
        OPENAI_MODEL environment variable

    Uses the current OpenAI Python SDK Responses API with structured
    JSON output. The exact model can be selected through OPENAI_MODEL.
    """
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError(
            "OpenAI SDK is not installed. Run: pip install openai"
        ) from exc

    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError(
            "OPENAI_API_KEY is not set. Use the local baseline mode first "
            "or configure your API key."
        )

    client = OpenAI()
    model = model or os.getenv("OPENAI_MODEL", "gpt-5.6-luna")

    source = load_source()
    instructions = load_prompt()
    source_text = build_extraction_input(source)

    response = client.responses.create(
        model=model,
        instructions=instructions,
        input=source_text,
        text={
            "format": {
                "type": "json_schema",
                "name": "candidate_commitments",
                "strict": True,
                "schema": {
                    "type": "object",
                    "properties": {
                        "candidate_commitments": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "candidate_id": {"type": "string"},
                                    "action": {"type": "string"},
                                    "object": {"type": "string"},
                                    "owner": {"type": ["string", "null"]},
                                    "owner_type": {
                                        "type": "string",
                                        "enum": ["MY_ACTION", "OTHER_ACTION", "UNKNOWN"]
                                    },
                                    "related_person": {"type": ["string", "null"]},
                                    "deadline_text": {"type": ["string", "null"]},
                                    "deadline_date": {"type": ["string", "null"]},
                                    "deadline_time": {"type": ["string", "null"]},
                                    "deadline_precision": {
                                        "type": "string",
                                        "enum": [
                                            "exact", "morning", "afternoon",
                                            "evening", "end_of_day", "day_only",
                                            "relative", "none"
                                        ]
                                    },
                                    "status": {
                                        "type": "string",
                                        "enum": [
                                            "OPEN", "COMPLETED",
                                            "CANCELLED", "UNCLEAR"
                                        ]
                                    },
                                    "ownership_ambiguous": {"type": "boolean"},
                                    "source_type": {
                                        "type": "string",
                                        "enum": [
                                            "meeting", "email",
                                            "calendar", "voice_note"
                                        ]
                                    },
                                    "source_reference": {"type": "string"},
                                    "source_date": {"type": ["string", "null"]},
                                    "evidence": {"type": "string"},
                                    "confidence": {
                                        "type": "string",
                                        "enum": ["high", "medium", "low"]
                                    }
                                },
                                "required": [
                                    "candidate_id", "action", "object",
                                    "owner", "owner_type", "related_person",
                                    "deadline_text", "deadline_date",
                                    "deadline_time", "deadline_precision",
                                    "status", "ownership_ambiguous",
                                    "source_type", "source_reference",
                                    "source_date", "evidence", "confidence"
                                ],
                                "additionalProperties": False
                            }
                        }
                    },
                    "required": ["candidate_commitments"],
                    "additionalProperties": False
                }
            }
        }
    )

    return json.loads(response.output_text)


def save_candidates(result, output_path=None):
    if output_path is None:
        output_path = Path(__file__).resolve().parent / "data" / "candidate_commitments.json"

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(result, file, indent=2, ensure_ascii=False)

    return output_path


def run_local_baseline():
    baseline_path = Path(__file__).resolve().parent / "data" / "candidate_commitments_baseline.json"
    with open(baseline_path, "r", encoding="utf-8") as file:
        result = json.load(file)

    output_path = save_candidates(result)
    print("Phase C baseline extraction completed.")
    print("Candidate records:", len(result["candidate_commitments"]))
    print("Saved:", output_path)


def main():
    use_llm = os.getenv("USE_LLM", "0") == "1"

    if use_llm:
        result = extract_with_openai()
        output_path = save_candidates(result)
        print("Phase C LLM extraction completed.")
        print("Candidate records:", len(result["candidate_commitments"]))
        print("Saved:", output_path)
    else:
        run_local_baseline()
        print("LLM mode is OFF. Set USE_LLM=1 after configuring OPENAI_API_KEY.")


if __name__ == "__main__":
    main()
